### PR TITLE
Included Images as well as made changes in Input Link

### PR DESCRIPTION
**Pull request by Monu2114**
To make the site look better, i included 3 images and hover effect on them. And I have implemented another functionality where user will see the link once he clicks on createLink. The Input Bar which was appearing on screen without user clicking on createLink was misleading so had to implement this.  Kindly view the changes.
image

### CODE REVIEW

**Comment by Monu2114** [comment]
Hey can you pls add this to the repo ??

**Comment by Monu2114** [comment]
heyy i am so sorry github is[image: image.png]
 a bit confusing for me... So this pull request was for issue #1 i raised
earlier regarding ui/ux .

**Comment by Monu2114** [comment]
Hey i am sorry to irritate but I forgot to assign #1 to my pr. Pls re
assign and add those labels plss

**Comment by Monu2114** [comment]
Heyy pls look into this... My code for #1 got merged but I forgot to tag
the issue so i didn't get my 25 points. I have emailed you multiple times
earlier pls look into this

**Comment by Monu2114** [comment]
@Soumojitshome2023 hey pls label this pull request as label2 i didnt link the issue as i was new to github i didnt knew. pls man. I have emailed u multiple times

**Comment by MastanSayyad** [comment]
@Soumojitshome2023 Please have a look on it, and be active on your repository.

**Comment by Monu2114** [comment]
heyy pls look into this issue ? not resolved yet @Mastan Sayyad
***@***.***>

**Pull request merged**
